name: 'sharadar'
version: '1.0.0'
config-version: 2

profile: 'sharadar'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
packages-install-path: "{{ env_var('APP_ROOT', env_var('PWD')) }}/dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"


models:
  sharadar:
    +materialized: view
    mart:
     +materialized: table


on-run-end: 
  - "{{ upload_dbt_results(results, 1000000) }}"