version: 2

models: 
  - name: actions_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_actions")
  - name: daily_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_daily")
  - name: events_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_events")
  - name: indicators_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_indicators")
  - name: sf1_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_sf1")
  - name: sp500_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_sp500")
  - name: tickers_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_tickers")
  - name: metrics_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_metrics")
  - name: sep_typed
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("stg_sep")