SELECT
"table",
permaticker,
ticker,
name,
exchange,
isdelisted,
category,
cusips,
siccode,
sicsector,
sicindustry,
famasector,
famaindustry,
sector,
industry,
scalemarketcap,
scalerevenue,
relatedtickers,
currency,
location,
CAST(strptime(lastupdated, '%Y-%m-%d') AS DATE) as lastupdated,
CAST(strptime(firstadded, '%Y-%m-%d') AS DATE) as firstadded,
CAST(strptime(firstpricedate, '%Y-%m-%d') AS DATE) as firstpricedate,
CAST(strptime(lastpricedate, '%Y-%m-%d') AS DATE) as lastpricedate,
CAST(strptime(firstquarter, '%Y-%m-%d') AS DATE) as firstquarter,
CAST(strptime(lastquarter, '%Y-%m-%d') AS DATE) as lastquarter,
secfilings,
companysite
FROM
{{ ref('stg_tickers') }}