SELECT
    table,
    permaticker,
    ticker,
    name,
    exchange,
    isdelisted,
    category,
    cusips,
    siccode,
    sicsector,
    sicindustry,
    famasector,
    famaindustry,
    sector,
    industry,
    scalemarketcap,
    scalerevenue,
    relatedtickers,
    currency,
    location,
    secfilings,
    companysite,
    CAST(STRPTIME(lastupdated, '%Y-%m-%d') AS DATE) AS lastupdated,
    CAST(STRPTIME(firstadded, '%Y-%m-%d') AS DATE) AS firstadded,
    CAST(STRPTIME(firstpricedate, '%Y-%m-%d') AS DATE) AS firstpricedate,
    CAST(STRPTIME(lastpricedate, '%Y-%m-%d') AS DATE) AS lastpricedate,
    CAST(STRPTIME(firstquarter, '%Y-%m-%d') AS DATE) AS firstquarter,
    CAST(STRPTIME(lastquarter, '%Y-%m-%d') AS DATE) AS lastquarter
FROM
    {{ ref('stg_tickers') }}
