name: Update Sharadar Data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

env:
  GITHUB_PAT: ${{ secrets.GH_PAT }}

jobs:
  refresh_sharadar:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      -
        name: Install dependencies
        run: |
          bash install_deps.sh
      -
        name: Sync sharadar raw to dev and prod
        run: |
          make ingest-sharadar
      -
        name: dbt build dev
        run: |
          make dbt-build TIER=dev
      -
        name: dbt build prod
        run: |
          make dbt-build TIER=prod
      - 
        name: Export prod db
        run: |
          pipenv run python -c "import duckdb; duckdb.connect(database='/data/antirank/prod.duckdb', read_only=True).execute(\"EXPORT DATABASE '/data/antirank/export/' (FORMAT PARQUET)\")"